# Generated by Django 2.1 on 2019-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190221_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
