# Generated by Django 2.1 on 2019-02-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190222_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=400),
        ),
    ]
